[package]
name = "mclanfake"
version = "0.1.0"
authors = ["Niklas Elsbrock <mail@nelsbrock.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "fat"
codegen-units = 1

[dependencies]
clap = "3.0.0-beta.2"